export const investmentCaseContent = {
  hero: {
    eyebrow: "Diligence rationale",
    title: "Why Kafwego merits diligence",
    subtitle:
      "An early-stage exploration opportunity with multiple converging geological indicators, a defined target portfolio and a clear, bounded near-term technical test.",
  },

  features: [
    {
      title: "Geological address",
      body: "Kafwego sits within the Greater Lufilian Arc in northwestern Zambia, an established copper mining region with a long history of exploration, development and operating capability.",
    },
    {
      title: "Converging exploration evidence",
      body: "The case combines surface Cu-Au-Ag mineralisation, iron-oxide alteration, quartz veining, structural interpretation and a district-scale aeromagnetic anomaly, rather than relying on a single signal.",
    },
    {
      title: "Multiple targets",
      body: "Five priority target areas provide more than one opportunity to test the underlying geological hypothesis, so the thesis does not stand or fall on a single drill location.",
    },
    {
      title: "Clear near-term catalyst",
      body: "The planned 750 m RC programme is designed to provide the first systematic subsurface test of the priority targets and to materially change what is known about the project.",
    },
    {
      title: "Bounded technical question",
      body: "The immediate question is not whether Kafwego supports mine development. It is whether drilling validates enough of the model to justify substantially more exploration.",
    },
    {
      title: "Stage-gated capital deployment",
      body: "Each stage is scoped to answer a specific technical question, and further spending should be driven by the evidence generated by the preceding phase rather than by a predetermined schedule.",
    },
  ],

  partnership: {
    eyebrow: "Partnership",
    title: "Partnership pathways",
    paragraphs: [
      "Kafwego is evaluating strategic funding and partnership structures for the next phase of exploration. Potential structures will depend on partner profile, scope of participation and agreed project objectives.",
      "Detailed commercial discussions are available to qualified counterparties following initial technical diligence.",
    ],
    note: "No commercial terms, ownership percentages or earn-in mechanics are represented on this website.",
  },

  funding: {
    eyebrow: "Funding",
    title: "Next-phase funding",
    body: "Kafwego is engaging qualified investors and strategic partners around the next exploration phase. Detailed programme scope, budget and partnership structure are available through the technical diligence process.",
  },

  diligence: {
    eyebrow: "Process",
    title: "How diligence proceeds",
    steps: [
      "Request the technical package",
      "Technical review and discussion",
      "Extended diligence access",
      "Commercial discussion",
      "Site visit and next-step process",
    ],
  },
};
