/**
 * Deliberately restrained. Only claims supported by work actually undertaken.
 *
 * The previous version of this page asserted community value creation, skills
 * transfer, local employment and supplier development. No evidence for those
 * activities exists in the project technical material, so they have been removed
 * rather than reworded. Forward-looking intentions are labelled as principles.
 */
export const responsibleDevelopmentContent = {
  hero: {
    eyebrow: "Responsible exploration",
    title: "Responsible exploration begins before drilling",
    subtitle:
      "Kafwego is an exploration-stage project that has not yet drilled. Current work includes progressing the relevant environmental and regulatory requirements alongside technical programme preparation.",
  },

  current: {
    eyebrow: "Current position",
    title: "What is actually underway",
    pillars: [
      {
        title: "Environmental and regulatory readiness",
        body: "Environmental approvals and licensing work are being progressed in preparation for field activities. This work is in progress and is not complete.",
      },
      {
        title: "Programme design",
        body: "QA/QC procedures and staged exploration milestones have been developed as part of the drilling programme design, so that data generated by the programme is verifiable.",
      },
    ],
  },

  principles: {
    eyebrow: "Principles",
    title: "Principles for later stages",
    intro:
      "The following are stated intentions for how the project would be advanced, not descriptions of work already carried out. They are included so that counterparties understand the intended operating approach.",
    pillars: [
      {
        title: "Regulatory alignment",
        body: "Work programmes are intended to be advanced in accordance with applicable Zambian regulatory requirements and permitting pathways.",
      },
      {
        title: "Controlled field practice",
        body: "Field activities are intended to be conducted under defined environmental controls appropriate to the scale of exploration being undertaken.",
      },
      {
        title: "Stakeholder engagement",
        body: "Engagement with relevant local and regulatory stakeholders is intended to be treated as a continuous operating process as field activity begins.",
      },
    ],
  },
};
